// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using norcam.Data;

namespace norcam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201217041149_Models")]
    partial class Models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("norcam.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<string>("fax")
                        .HasColumnType("text");

                    b.Property<string>("razon_social")
                        .HasColumnType("text");

                    b.Property<string>("ruc")
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("norcam.Models.Facturas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("adval")
                        .HasColumnType("double precision");

                    b.Property<string>("archivo")
                        .HasColumnType("text");

                    b.Property<double>("cif")
                        .HasColumnType("double precision");

                    b.Property<double>("comision")
                        .HasColumnType("double precision");

                    b.Property<string>("dua")
                        .HasColumnType("text");

                    b.Property<string>("factura")
                        .HasColumnType("text");

                    b.Property<string>("fec_canc")
                        .HasColumnType("text");

                    b.Property<string>("fec_fac")
                        .HasColumnType("text");

                    b.Property<double>("gasto_admin")
                        .HasColumnType("double precision");

                    b.Property<double>("gasto_ope")
                        .HasColumnType("double precision");

                    b.Property<double>("igv")
                        .HasColumnType("double precision");

                    b.Property<double>("igv_2")
                        .HasColumnType("double precision");

                    b.Property<double>("ipm")
                        .HasColumnType("double precision");

                    b.Property<double>("reintegro")
                        .HasColumnType("double precision");

                    b.Property<double>("sup_cont")
                        .HasColumnType("double precision");

                    b.Property<double>("tc")
                        .HasColumnType("double precision");

                    b.Property<double>("total_liq")
                        .HasColumnType("double precision");

                    b.Property<double>("total_neto")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("norcam.Models.Ordenes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("contenido")
                        .HasColumnType("text");

                    b.Property<string>("fec_entrega")
                        .HasColumnType("text");

                    b.Property<string>("fec_num")
                        .HasColumnType("text");

                    b.Property<string>("fec_rec")
                        .HasColumnType("text");

                    b.Property<int?>("id_clienteid")
                        .HasColumnType("integer");

                    b.Property<string>("peso")
                        .HasColumnType("text");

                    b.Property<string>("proveedor")
                        .HasColumnType("text");

                    b.Property<string>("regimen")
                        .HasColumnType("text");

                    b.Property<string>("ubicacion")
                        .HasColumnType("text");

                    b.Property<double>("valor_num")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.HasIndex("id_clienteid");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("norcam.Models.Ordenes", b =>
                {
                    b.HasOne("norcam.Models.Cliente", "id_cliente")
                        .WithMany()
                        .HasForeignKey("id_clienteid");
                });
#pragma warning restore 612, 618
        }
    }
}
